### ISSUE TITLE
Code does not match what is released in NPM

### ISSUE THREAD

**Issue by dimitarnestorov** [electron-userland/electron-installer-snap#1]
I just published it to my private repo and it worked. So I guess a version bump and a republish will do the trick.

**Comment by develar** [comment]
Canonical recommends using [electron-builder](https://github.com/electron-userland/electron-builder) to build snap. 

`electron-builder --linux snap` 

If you use electron-forge — please use [electron-forge-maker-snap](https://www.npmjs.com/package/electron-forge-maker-snap) 
or simply `electron-builder --prepackaged <your out dir>`

**Comment by zeke** [comment]
@malept was hired by Canonical to work on an official Snap installer for Electron, and this repo represents that work. However, the module published to `electron-installer-snap` is actually just a squatted package that points to electron-builder. @develar has added me as an owner of `electron-installer-snap` so we can rectify this confusion.

I propose:

1. `npm owner add malept electron-installer-snap`
1. @malept can publish a new major version bump of the module from this repo.

**Comment by dimitarnestorov** [comment]
I stumbled upon more issues after republishing this to my private repo and I spent several hours figuring out how to fix some errors while trying https://github.com/electron-userland/electron-builder. I'm proposing for at least a `README.md` update to point people to use https://github.com/electron-userland/electron-builder and a `npm deprecate`

**Comment by malept** [comment]
> I stumbled upon more issues after republishing this to my private repo and I spent several hours figuring out how to fix some errors

If you could file some bugs, that would be helpful. I have a TODO list that I haven't committed, but it should work for the base case.

**Comment by dimitarnestorov** [comment]
I remember that this https://github.com/electron-userland/electron-installer-snap/blob/master/src/default_args.js#L45 was returning a promise and I just patched it to `pathExistsSync` and I think after that I stumbled upon more problems (can't remember what they were) which led me to try electron-builder again.

**Comment by develar** [comment]
I propose to continue our discussion https://github.com/electron-userland/electron-forge/issues/25 (@zeke or @MarshallOfSound didn't answer me to email/slack). To avoid user confusion. Snapcraft team contributes to electron-builder (e.g. https://github.com/electron-userland/electron-builder/pulls?utf8=✓&q=is%3Apr+author%3Aflexiondotorg) and electron-builder also can produces snap on any OS.

@flexiondotorg In any case we all will discuss it on Snapcraft summit, right :)?

**Comment by flexiondotorg** [comment]
Yes, since @develar, @malept and I will all be at the Snapcraft Summit I think that is a perfect time to discuss this 😀

**Comment by zeke** [comment]
> @zeke ... didn't answer me to email/slack

Sorry about that. I was not following the forge repo, and I don't think I was pinged on that issue.

> Snapcraft Summit I think that is a perfect time to discuss this

👍 let me know how that goes!

**Comment by malept** [comment]
`electron-installer-snap` 2.0.0 has been released to NPM, which is the same as the [`v2.0.0`](https://github.com/electron-userland/electron-installer-snap/releases/tag/v2.0.0) tag.

**Comment by develar** [comment]
> let me know how that goes

electron-installer-snap is a lightweight tool to build snap if someone doesn't want to use relatively heavy-weight forge/builder. electron-builder offers a more easy and user-friendly way:
* build on any OS (macOS: docker or build service, windows: build service or docker, Linux that doesn't support snapcraft: docker or build service).
* as soon as new version of snapcraft will be released, building without docker on macOS (if no custom packages (covers most of the Electron apps)).
* build on any supported Ubuntu version if no custom packages (so, you can use Ubuntu 17+ to build snap that will be guaranteed to work on Ubuntu 16).
* reduced build time (if no custom package).
* lack of vendor-lock (all common Linux options are shared across all Linux targets). In most cases you just need to set target to `snap` and nothing else.

Ideally, yes, it will be cool if both electron-builder and electron-installer-snap will reuse the same core code (minimum descriptor that required to create snap for Electron app) to build snap, but reality is that this core code is small (though is quite critical and complex (set of default packages and other tricky parts)) and not changed often. And most of the code it is just a boring wrapper.

The only goal for me — to make sure that user have a clear picture what and when use some tool. To avoid user confusion. As upcoming Electron docs about building snap contains such note, I am happy with current situation.
