### ISSUE TITLE
Can't convert packaged app to snap.

### ISSUE THREAD

**Issue by ncodeyx** [electron-userland/electron-installer-snap#45]
* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-installer-snap/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Please describe your issue:**
I am trying to convert my Electron app that was built by electron-packager on Linux x64, but it fails.

**Console output when you run electron-installer-snap with the environment variable `DEBUG='electron-installer-snap:*'`. Please include the stack trace if one exists.**

```
codey@codey:~/Desktop/electronpw/PenguinWorld-linux-x64$ npx electron-installer-snap DEBUG='electron-installer-snap:*'
npx: installed 76 in 4.627s
Cloning into '/tmp/electron-snap-307026TRYHqIGjFtT/parts/desktop-gtk3/src'...
remote: Enumerating objects: 37, done.        
remote: Counting objects: 100% (37/37), done.        
remote: Compressing objects: 100% (33/33), done.        
remote: Total 1387 (delta 9), reused 20 (delta 2), pack-reused 1350        
Receiving objects: 100% (1387/1387), 261.40 KiB | 966.00 KiB/s, done.
Resolving deltas: 100% (715/715), done.
(node:30702) UnhandledPromiseRejectionWarning: Error: Exited with status 2
    at closeArgsToError (/home/codey/.npm/_npx/30702/lib/node_modules/electron-installer-snap/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/home/codey/.npm/_npx/30702/lib/node_modules/electron-installer-snap/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
(node:30702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What command line arguments are you passing? Alternatively, if you are using the API, what
parameters are you passing to the `snap()` function?**

```
npx electron-installer-snap 
```
in the packaged directory

Am I missing or not doing something correctly?

**Comment by malept** [comment]
Without knowing what the debug information is _(see the section on [debugging](https://github.com/electron-userland/electron-installer-snap/blob/master/CONTRIBUTING.md#debugging) in our docs)_, I can only speculate as to what the problem is. My guess is that it's failing since the `base` isn't set and you're using a relatively recent version of Linux (e.g., not Ubuntu 16.04). #47 will autodetect the value for you if it isn't set already.

If this isn't the case, please supply the appropriate debugging information per the docs and we can try to determine what's actually wrong.
